'use strict';
// A command contributed in package.json but never registered shows up in the
// palette and then fails with "command 'npmScriptLens.x' not found" when it is
// picked. A command registered but not contributed is invisible. Neither shows
// up in any other test here, because the palette is VS Code's side of the
// contract and nothing in this repo exercises it.
//
// So: read both sides and diff them. This is what catches a new CLI surface
// gaining a palette entry without a handler, or the other way round.
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const extension = fs.readFileSync(path.join(ROOT, 'src', 'extension.js'), 'utf8');

const declared = pkg.contributes.commands.map((c) => c.command).sort();
// registerCommand goes through one `cmd(name, fn)` helper, so the registration
// site is a literal and can be read statically.
const registered = [...extension.matchAll(/\bcmd\('([\w.]+)'/g)].map((m) => m[1]).sort();

test('every contributed command is registered, and every registration is contributed', () => {
  assert.deepStrictEqual(registered, declared);
});

test('every command a menu, welcome view or walkthrough points at exists', () => {
  const referenced = new Set();
  const walk = (node) => {
    if (typeof node === 'string') {
      for (const m of node.matchAll(/command:(npmScriptLens\.[\w.]+)/g)) referenced.add(m[1]);
      return;
    }
    if (Array.isArray(node)) { node.forEach(walk); return; }
    if (node && typeof node === 'object') {
      for (const [key, value] of Object.entries(node)) {
        if (key === 'command' && typeof value === 'string') referenced.add(value);
        else walk(value);
      }
    }
  };
  walk(pkg.contributes.menus);
  walk(pkg.contributes.viewsWelcome);
  walk(pkg.contributes.walkthroughs);

  const known = new Set(declared);
  // the panel's focus command is generated by VS Code from the view id, so it
  // is neither contributed nor registered here
  known.add('npmScriptLens.packages.focus');
  const missing = [...referenced].filter((c) => !known.has(c)).sort();
  assert.deepStrictEqual(missing, []);
});

test('every command title is namespaced or is an inline row action', () => {
  // Palette entries have to carry the extension name or they are unfindable;
  // the two inline row icons deliberately do not, because they render next to
  // the row rather than in a list.
  const inline = new Set(['npmScriptLens.approve', 'npmScriptLens.block']);
  for (const c of pkg.contributes.commands) {
    if (inline.has(c.command)) continue;
    assert.ok(c.title.startsWith('npm-script-lens: '), `${c.command}: ${c.title}`);
  }
});

test('the extension version tracks the CLI it shells out to', () => {
  // Deliberate since 1.15.0: "Version numbering now tracks the CLI again".
  const cli = JSON.parse(fs.readFileSync(path.join(ROOT, '..', '..', 'package.json'), 'utf8'));
  assert.strictEqual(pkg.version, cli.version);
});
